version: '3'

services:
  tsm_mysql:
    image: mysql:latest                     #Image of mysql 
    container_name: tsm_mysql               #Set container name     
    
    environment:                            #environment variables for env
      MYSQL_DATABASE: kt_laravel_db
      MYSQL_USER: kt_laravel_user
      MYSQL_PASSWORD: kt_laravel_password

    volumes:                                #Mount container data to docker volumes for permanent
      - tsm_mysql_volume:/var/lib/mysql
      
    networks:                               #Set network for container
      tsm_network

  tsm_php:
    build:                                                  #Build specific image
      dockerfile: devops/docker/php8.1-fpm.dockerfile       #dockerfile path  
    image: todo_php:8.1-fpm                                 #image name for new docker image
    container_name: tsm_php
    volumes:                                                #volume mounting for logs
      - ./:/var/www/html                                     
      - ./logs/:/var/www/html/storage/logs
    depends_on:                                             
      - tsm_mysql
    networks:
      - tsm_network

  tsm_nginx:
    image: nginx:latest
    container_name: tsm_nginx
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./devops/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - tsm_php
    networks:
      - tsm_network


networks:
  tsm_network:
    driver: bridge
      #ipam:
      # config:
      #   -subnet: 10.10.0.0/16  


volumes:
  tsm_mysql_volume: